"""add items table

Revision ID: 44a4aa917140
Revises: 304dae6663a3
Create Date: 2025-01-01 00:10:00.000000

"""

import uuid
from datetime import datetime, timezone

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "44a4aa917140"
down_revision = "304dae6663a3"
branch_labels = None
depends_on = None

now = datetime.now(timezone.utc)
mock_items = [
    {
        "id": str(uuid.uuid4()),
        "name": "Wireless Mouse",
        "description": "Ergonomic wireless mouse with adjustable DPI",
        "price": 350000,
        "quantity": 50,
        "sku": "WM-001",
        "created_at": now,
        "modified_at": now,
        "deleted_at": None,
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Mechanical Keyboard",
        "description": "RGB mechanical keyboard with blue switches",
        "price": 1200000,
        "quantity": 30,
        "sku": "MK-002",
        "created_at": now,
        "modified_at": now,
        "deleted_at": None,
    },
    {
        "id": str(uuid.uuid4()),
        "name": "Gaming Headset",
        "description": "Surround sound gaming headset with microphone",
        "price": 950000,
        "quantity": 20,
        "sku": "GH-003",
        "created_at": now,
        "modified_at": now,
        "deleted_at": None,
    },
    {
        "id": str(uuid.uuid4()),
        "name": "USB-C Hub",
        "description": "7-in-1 USB-C hub with HDMI and SD card reader",
        "price": 800000,
        "quantity": 40,
        "sku": "UH-004",
        "created_at": now,
        "modified_at": now,
        "deleted_at": None,
    },
    {
        "id": str(uuid.uuid4()),
        "name": "External SSD 1TB",
        "description": "Portable 1TB SSD with USB 3.2 connection",
        "price": 2500000,
        "quantity": 15,
        "sku": "ES-005",
        "created_at": now,
        "modified_at": now,
        "deleted_at": None,
    },
]

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    items_table = op.create_table(
        "items",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("items_pkey")),
    )
    op.create_index(op.f("ix_items_created_at"), "items", ["created_at"], unique=False)
    op.create_index(op.f("ix_items_deleted_at"), "items", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_items_name"), "items", ["name"], unique=False)
    op.create_index(op.f("ix_items_sku"), "items", ["sku"], unique=True)
    op.bulk_insert(items_table, mock_items)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_items_sku"), table_name="items")
    op.drop_index(op.f("ix_items_name"), table_name="items")
    op.drop_index(op.f("ix_items_deleted_at"), table_name="items")
    op.drop_index(op.f("ix_items_created_at"), table_name="items")
    op.drop_table("items")
    # ### end Alembic commands ###
